### ISSUE TITLE
Add CSS Modules to webpack

### ISSUE THREAD

**Issue by ro-savage** [in-depth/indepth-core#1]
We should add CSS Modules to the webpack build. It should just need to through a CSS Module loader.

Here is an example from a previous project

``` js
      // Any .scss file in ./src/... *except* those in ./src/styles/
      // are local css modules. the class names and ids will be changed to:
      // [name]-[local]-[hash:base64:5]
      // include: /src\/(?!styles).+/,
      {
        test: /.css/,
        exclude: /src\/styles|react-data-grid|\/styles\.css/,
        loaders: [
          'style',
          'css?modules&sourceMap&importLoaders=1&localIdentName=[name]-[local]-[hash:base64:5]',
        ],
      },
```

The final result is when you run the project and look at a class style, it should have a special postfix.

To import the style
`import styles from ComponentName.css`
To use it with in an element is
`style={styles.newClass}`

**Comment by nickmask** [comment]
Closed by PR #4
