### ISSUE TITLE
Add PostCSS

### ISSUE THREAD

**Issue by ro-savage** [in-depth/indepth-core#2]
We need to add PostCSS to our project, rather than SASS.

It should be implemented through a loader in webpack.

I am unsure how to implement this, you'll need to see the docs for PostCSS and Webpack.

We should use:
 [PostCSS Values](https://github.com/css-modules/postcss-modules-values)
 [cssNext](http://cssnext.io/)
 [Fluid Properties](http://www.adrenalinmedia.com.au/blog/january-2016/this-changes-everything-css-%E2%80%98fluid-properties%E2%80%99) [Link2](https://gist.github.com/gerardmrk/083f19c4b63cf241620d)
We also need some way to handle nesting like SASS and check how to import a 'config' file into each stylesheet (maybe [postcss-imports](https://github.com/postcss/postcss-import))
- [x] Runs through PostCSS
- [x] Runs CSS Modules / PostCSS Values
- [x] Runs cssNext
- [ ] Runs Fluid Properties
- [x] Has nesting features
- [x] Has import

This does not have been done in one go. We can do it as we want to use though features

**Comment by nickmask** [comment]
Closed by PR #7
